image: inetsix/docker-ansible:2.7

stages:
  - build
  - analysis
  - test
  - diff
  - push
  - clean

#######################
# Template management #
#######################

.test_ansible_bootstrap: &test_ansible_bootstrap
  before_script:
    - source .venv/bin/activate
    - chmod 755 examples
    - cd examples


#######################
# CI MANAGEMENT       #
#######################

ENVIRONMENT.BUILD:
  stage: build
  script:
    - pip install virtualenv
    - virtualenv -p $(which python) .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - cp CVPRACv2/* .venv/lib/python2.7/site-packages/cvprac/
    - ls -a .venv/lib/python2.7/site-packages/cvprac/
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .venv/

ENVIRONMENT.VERSION:
  stage: analysis
  script:
    - source .venv/bin/activate
    - ansible --version
    - python --version
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .venv/

CVPRAC.ENHANCED:
  stage: test
  script:
    - source .venv/bin/activate
    - sh .ci/check_cvprac.sh
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .venv/

CVP_MODULE.LOAD:
  stage: test
  <<: *test_ansible_bootstrap
  script:
    - ansible-doc -t module cv_device
    - ansible-doc -t module cv_container
    - ansible-doc -t module cv_configlet
    - ansible-doc -t module cv_image
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .venv/
