name: Code Sanity
on: 
  push:
    branches:
      - 'issues/*'
      - 'features/*'

jobs:
  python-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup dev environment
      run: make setup-repository
    - name: Run python-linting 
      run: make linting