name: Commit check
on:
  push:
  pull_request:
jobs:
  'pre-commit':
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    container: avdteam/base:3.6
    steps:
      - uses: actions/checkout@master
      - name: test pre-commit
        run: |
          pip list | grep pre-commit
          ls -al /root/.local/bin/ | grep pre
          pre-commit help
      - name: 'Pre Commit run'
        run: |
          make pre-commit
