name: Ansible Molecule
on:
  push:
  pull_request:
    paths:
      - 'ansible_collections/arista/cvp/roles/**/*'
      - 'ansible_collections/arista/cvp/molecules/**/*'
      - 'requirements.txt'
      - '.github/workflows/molecule.yml'
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    strategy:
      fail-fast: true
      matrix:
        python_version: [ 3.6 ]
        avd_scenario:
          - dhcp_configuration
          - cv_configlet
          - cv_device
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements.txt
          pip install -r development/requirements-dev.txt

      - name: Execute molecule
        run: |
          cd ansible_collections/arista/cvp
          molecule test --destroy=never  --scenario-name ${{ matrix.avd_scenario }}
          ls -alR molecule

      - name: Test molecule results
        run: |
          pwd
          cd ansible_collections/arista/cvp/
          ls -alR

      - uses: actions/upload-artifact@v1
        with:
          name: molecule-results-${{ matrix.avd_scenario }}
          path: ansible_collections/arista/cvp/molecule/${{ matrix.avd_scenario }}
