name: Collection Publication
on:
  push:
    tags:
      - 'v**'
jobs:
  local_build:
    name: Build Ansible CVP Collection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Install packages'
        run: |
          make setup-repository
      - name: 'Ansible Galaxy build'
        run: |
          make collection-build
      - uses: actions/upload-artifact@v1
        with:
          name: collection-package
          path: ansible-cvp*